//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadEmployeePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoadEmployeePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///  &quot;users&quot;: [
        ///    {
        ///      &quot;id&quot;: 1,
        ///      &quot;firstName&quot;: &quot;Emily&quot;,
        ///      &quot;lastName&quot;: &quot;Johnson&quot;,
        ///      &quot;maidenName&quot;: &quot;Smith&quot;,
        ///      &quot;age&quot;: 28,
        ///      &quot;gender&quot;: &quot;female&quot;,
        ///      &quot;email&quot;: &quot;emily.johnson@x.dummyjson.com&quot;,
        ///      &quot;phone&quot;: &quot;+81 965-431-3024&quot;,
        ///      &quot;username&quot;: &quot;emilys&quot;,
        ///      &quot;password&quot;: &quot;emilyspass&quot;,
        ///      &quot;birthDate&quot;: &quot;1996-5-30&quot;,
        ///      &quot;image&quot;: &quot;https://dummyjson.com/icon/emilys/128&quot;,
        ///      &quot;bloodGroup&quot;: &quot;O-&quot;,
        ///      &quot;height&quot;: 193.24,
        ///      &quot;weight&quot;: 63.16,
        ///      &quot;eyeColor&quot;: &quot;Green&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string dummyjson {
            get {
                return ResourceManager.GetString("dummyjson", resourceCulture);
            }
        }
    }
}
